# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Yinjie Wang"
weight = 1
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "王胤杰"
weight = 1
