# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1
[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "示例网站"
weight = 1
